<a href="https://colab.research.google.com/github/N1ck1103/stunning/blob/main/Nicholas_Smith_Copy_of_Hahn_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
import numpy as np # import numpy tells the code to bring along the NumPy library into your current notebook
import matplotlib.pyplot as plt # is a collection of command style functions that make matplotlib work like matlab 
import imageio #provides an easy interface to read and write a wide range of image data, including animated images, volumetric data, and scientific formats
from PIL import Image #python imaging library import images

In [2]:
for i in range(100):  # i is set to a range of 100 numbers starting from 0 so we see 0-99
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [3]:
for i in range(5,8): # This means that it only wants the numbers in the range 5-8 meaning that we will get 5,6,7 printed out 
    print(i)

5
6
7


In [4]:
for i in range(3):  # i is now range up to three and is printed as "Test Number: ", i
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [5]:
def square(x): # when square(x) is called it will return X**2
    return x**2

In [6]:
square(5) # here is an example we see 5 is covered for x and we get 25 

25

In [7]:
square(square(2)) # Here we see square being called twice meaning that the number two will be squared once giving us 4 and then squared again giving us 16 like saying 2 to the third power

16

In [8]:
square(square(square(2))) # same thing as the last except this time 2 is squared 3 times almost like saying two to the 4th power 


256

In [9]:
square(123456) # this number is just squared 

15241383936

In [10]:
square(square(5)) # 5 is squared once and then squared again technically 5 to the third power

625

In [11]:
def add_two(x): # this will return whatever number x wants to be with it being added by two 
    return x+2

In [12]:
add_two(5) # this means that 5 is the x and that it adds two 

7

In [13]:
square(add_two(5)) # 5 is added with 2 and then squared so we have 7 to the second power giving us 49 

49

### Logical Branching

In [14]:
choice = "apple" # choice is assigned with "apple" when called upon 

In [15]:
if choice == "apple": # this is an if else statment that returns two things one being "you choose apples." or "you did not choose apples."

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [16]:
choice = "orange" # choice is now being assigned another variable which is "orange"

In [17]:
if choice == "apple": # in this if else statement if apple is called "you choose apples." if apples is not called "you did not choose apples."


    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [18]:
choice = "apple" # choice is assined again to apple 

In [19]:
if choice == "apple": # 3 loop if else statemtn that if apples is the choice you have three things that will print out "You choose apples." "Thank you, shop again!" "2**123"

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange": # if apples is chosen you ge these two option below 

    print("You choose oranges.")
    print("Thank you, shop again!")

else: # if you don't get either one you get these two lines printed below 
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [20]:
choice = input("Please enter your choice (i.e. apple): ") # choice is assigned to an input that "Please enter your choice (i.e.apple): " The input puts an input bar below 

Please enter your choice (i.e. apple): apples


In [21]:
choice # expresses what the user chose

'apples'

In [22]:
if choice == "apple": # another 3 loop and concludes with apple being the users choice giving us the return statement "you choose apples."

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


#### Coins

In [23]:
np.random.random()# this produces a random number 

0.18078684478880236

In [24]:
np.random.random() > 0.5 # is the number above greater than 0.5 no so it is false 

False

In [25]:
def flip_coin(): # if els statment that means that if the random number is greater it is heads if it is less its tails 
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [26]:
flip_coin() # when flip_coin is called we get heads instead of tails meaning that it is less than 0.5

Heads


### Graphics Output

In [27]:
from IPython.core.display import display, HTML #import HTML capabilities

In [28]:
display(HTML('<h1>Hello, world!</h1>')) # simple html code that has a header to display "hello world"

In [29]:
def coin(): #coin is a return of low integers up to 2 
  return np.random.randint(2)

In [30]:
coin() # we see as coin() is called we get one 

1

In [31]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) # with the use of html we are able to display an image

In [32]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #This assigns the two names heads and tails with heads having the link to the heads image and with tails having the link with the tails link. 
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [33]:
def show_img(img): # this means that when this is called we will see both images the heads image and tails image 
  display(HTML('<img src=' + img + '>'))

In [34]:
show_img(heads)

In [35]:
show_img(tails)

In [36]:
def flip_coin(): # Flip_coin() is expressed as a if else statement meaning that if the random integer from 1-2 comes out depending on which number we will see the heads image or we will see the tails image. 

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [37]:
flip_coin()

In [38]:
for i in range(5): # this shows flip_coin() in a range of five flips. 
    flip_coin()

In [81]:
#@title Coin Flip

if coin(): # this is the whole process of the if else statement of the coin flipping we will either see heads or tails pop up 

  show_img(heads)

else:

  show_img(tails)

### Cards

In [40]:
def shuffle(x): #
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [41]:
a = np.arange(52) # a is aranged into 52 numbers 

In [42]:
shuffle(a) #shuffle a literally shuffles the 52 numbers 

array([41, 36,  5, 21, 40, 48, 44, 34, 42, 49, 10, 14, 25, 26,  8, 37, 11,
        3, 46, 38, 16, 18, 20,  0, 15, 47, 35, 17, 50, 28, 43, 13, 24,  2,
        4, 39, 23, 22, 19,  9,  7, 27, 29, 33,  6, 51, 31, 32, 45,  1, 30,
       12])

In [43]:
np.random.permutation(52) # this does the same thing shuffling the 52 numbers 

array([20, 46, 19, 39, 23, 17, 41, 35, 11, 12, 31,  7,  9, 36, 48,  5, 22,
       49,  0, 24,  2, 18, 42, 16, 26, 37, 28,  4, 51, 32, 21,  6, 30, 29,
       43, 50, 25,  3, 10,  1, 47, 45, 38, 15, 44, 34, 33, 14, 27, 40, 13,
        8])

### Speed Test

In [44]:
%%timeit
shuffle(a)

137 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [45]:
%%timeit
np.random.permutation(52)

2.79 µs ± 214 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
import numpy as np

In [47]:
np.random.permutation(52)

array([ 5,  4, 13, 36, 12, 42, 40,  8, 11, 33, 41, 28, 44, 15, 30,  6, 21,
       23, 26, 14, 10, 51, 39,  2, 22, 29, 17, 25,  9,  7, 20, 16, 50, 49,
       32, 43, 37, 38, 24,  1, 45, 48,  0, 18, 35, 34, 46, 19, 31, 47,  3,
       27])

In [48]:
cards = np.random.permutation(52)

In [49]:
cards

array([43, 47, 10,  8, 50,  4, 35, 46, 12, 18, 17,  0,  2, 41, 25, 29, 33,
        5,  1, 49, 39,  6, 13, 32,  7, 22, 21, 20, 38,  9, 23, 31, 44, 45,
       42, 30, 28, 36, 19, 48, 34, 24, 16, 14, 27,  3, 40, 15, 37, 51, 26,
       11])

In [50]:
cards[0]

43

In [51]:
cards[1]

47

In [52]:
cards[2]

10

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [53]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [54]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [55]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [56]:
suits = ['Clubs','Spades','Hearts','Diamonds']# array is created of suits of card playing deck
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #array is created of the values of the card playing deck

In [57]:
def card_name(card_number): #card_name is valued as both names and suits 
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [58]:
card_name(0) #card_name is called in the 0 spot meaining that we will receive Ace of clubs since they are in the 0 spot

'Ace of Clubs'

In [59]:
card_name(51) # the 51 array would be the king of diamonds

'King of Diamonds'

In [60]:
cards = np.random.permutation(52) #shuffles the cards up 

In [61]:
top_of_deck         = card_name(cards[0]) # gives value to top of the deck second card in deck and last card in deck 
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [62]:
top_of_deck, second_card_in_deck, last_card_in_deck # the shuffuled deck shows its first card second and last card 

('Four of Diamonds', 'Nine of Spades', 'Four of Spades')

In [63]:
for i in range(5): # five cards are now showed in random order 
    print(card_name(cards[i]))

Four of Diamonds
Nine of Spades
Eight of Clubs
Eight of Hearts
Three of Spades


In [64]:
for i in range(15): # now we do 15 random cards 
    print(card_name(cards[i]))

Four of Diamonds
Nine of Spades
Eight of Clubs
Eight of Hearts
Three of Spades
Seven of Clubs
Queen of Clubs
Six of Spades
Ace of Clubs
Ten of Clubs
Six of Hearts
Ace of Hearts
Six of Diamonds
Queen of Hearts
Seven of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [65]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [66]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [67]:
i = np.random.randint(4) # i is a random order of the four suit cards 
j = np.random.randint(13) # j is a random order of the 13 cards in the deck from ace to king 

In [68]:
i,j # we call i and j which randomly gives us 1,5 meaning we will get the first number in the suit variation giving us p and then we will get the 5th variation of card giving us 6

(1, 5)

In [69]:
suit[i]

'p'

In [70]:
card[j]

'6'

In [71]:
from IPython.core.display import display, HTML # imports html concepts 

In [72]:
def show_img(img): # this displays an image from html 
  display(HTML('<img src=' + img + '>'))

In [73]:
img = card_url_head + suit[i] + card[j] + card_url_tail # We now combine everything wehre we get the random suit and value along with the proper image attached to it 

In [74]:
show_img(img) # when img is called we get spade of 6 

In [75]:
def card_image(card_number): # card image gives us suit and card together 
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [76]:
card_image(3) #When this is called we get klover of four 

'k4'

In [77]:
img = card_url_head + card_image(3) + card_url_tail # sets image to all these added up 

In [78]:
show_img(img) # when we call img we get 4 of clover img 

In [79]:
for i in range(52): # now i is set to the 52 cards and we see the suits in order along with the values in order 
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)